<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5FESB8K" failures="1" tests="4" name="Test" time="39.791" errors="0" timestamp="2025-06-10T11:48:51 IST">
  <testcase classname="test.TC_001_SignUpTest" name="testValidSignUp" time="4.1"/>
  <testcase classname="test.TC_001_SignUpTest" name="testBlankUsername" time="4.105"/>
  <testcase classname="test.TC_001_SignUpTest" name="testBlankPassword" time="4.174"/>
  <testcase classname="test.TC_001_SignUpTest" name="testExistingUser" time="3.742">
    <failure type="java.lang.AssertionError" message="Existing user check failed. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Existing user check failed. expected [true] but found [false]
at test.TC_001_SignUpTest.testExistingUser(TC_001_SignUpTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testExistingUser -->
</testsuite> <!-- Test -->
